In [5]:
from numpy import *
arr1 = arange(1,15,1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
import numpy as np
arr1 = np.array([(1,2,3),
                 (4,5,6),
                 (7,8,9)])
print(arr1.sum(axis=0))

[12 15 18]


In [8]:
import numpy as np
arr1 = np.array([(1,2,3),
                 (4,5,6),
                 (7,8,9)])
print(arr1.sum(axis=1))

[ 6 15 24]


In [9]:
import numpy as np
arr1= np.array([2,3,1,5,6,7,])
print(arr1)

[2 3 1 5 6 7]


In [10]:
from numpy import *
arr1 = array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [11]:
from numpy import *
arr1 = array([1,2,3,4,5])

print(arr1.size)

5
